### ISSUE TITLE
Voting on Mac is not working. Image attached.

### ISSUE THREAD

**Issue by japoof** [hirishh/liskish-wallet#10]
<img width="898" alt="capture d ecran 2018-11-19 a 21 28 16" src="https://user-images.githubusercontent.com/45188757/48748889-759eb000-ec46-11e8-8945-1ce8e6b5f1cf.png">

**Comment by hirishh** [comment]
Hello @japoof 
thank you for this issue. Just a quick question: Did you use a vote manager? Or you just modified manually your votes? Do you remember how many vote-unvote you had?

I'm trying to reproduce the issue

**Comment by japoof** [comment]
Hi @hirishh , I used a vote manager (tried two different, one of them was https://lisk.builders/votemanager/). I was just trying to add votes for the first time on the Liskish wallet, so 33 up votes. Never worked. So that's it, thanks for your work!

**Comment by japoof** [comment]
@hirishh not sure how I can do that unfortunately, I'm pretty much beginning with this whole thing. That being said I entered the votes manually and it worked... so I guess as you said the problem lies in the API restrictions. Thanks again for your commitment!
