### ISSUE TITLE
Trezor no longer being detected

### ISSUE THREAD

**Issue by sabdon** [hirishh/liskish-wallet#15]
First off, thank you for this app, I really appreciate it.  I was able to use my trezor to login into liskish and use the app.  I was able to create a wallet, recieve funds, cast votes.  A few days have gone by and now i'm being met with an error and the hardware wallet is not being detected.  I'm running windows 10, lishish wallet version 2.0.3 beta. most recent trezor firmware.  I'm able to connect with my trezor to other wallets, and to the trezor wallet and see i have the latest bridge installed.  I've tried connecting the trezor first then opening the app.  Opening the app, then connecting trezor.  re-installing the bridge.  re-starting the computer. and I get the message "error or device not connected".

Please let me know if I can supply you with any additional information that would be useful.

Thanks!

**Comment by hirishh** [comment]
Hello @sabdon,

I'm sorry to hear that. I will try tonight on my windows machine but I'm quite sure I did it some days ago without any issue. I will try to help you to find the cause.

**Comment by sabdon** [comment]
@hirishh, thanks for the quick response.  The issue has to deal with the fact I am using a company computer.  It seems certain network settings were prohibiting the functionality.  Using a vpn resolves the issue for me.
