### ISSUE TITLE
No access to second initialized address

### ISSUE THREAD

**Issue by Leniwiec44** [hirishh/liskish-wallet#16]
I use Ledger Nano S for 2 different accounts (index 0 and 1) and by hw address discovery i can't see my second address (index 1) any more. Both of them are initialized. Last time i sent some founds to that account in June and everything was just fine. So now i have no access to the part of my founds. I use Liskish Wallet v.2.0.3 and Ledger firmware 1.5.5. What happened? Please help.

**Comment by hirishh** [comment]
Hello @Leniwiec44 

Could you please share a screenshot when you open the Address Discovery window? Is it possible that Lisk Official nodes implements an anti-flood mechanism that break the address discovery. I will do some test. Your funds are safe anyway of course.

**Comment by Leniwiec44** [comment]
Hello @hirishh 

Thanks for the quick answer. When i click on Create new account i got the message " Please use the last not-initialized account before creating a new one!" but it's normal i think. 
![Clipboard01](https://user-images.githubusercontent.com/54898675/64270065-3a524100-cf3b-11e9-8f2d-cf05ebc46079.jpg)

**Comment by Leniwiec44** [comment]
Last time when i logged in i used a twin ledger (same seeds) which is on another location now. And this is the 2nd address i have no access to:
https://explorer.lisk.io/address/3742961519243258051L

**Comment by hirishh** [comment]
ok that 0 at Transaction is very weird and that's the issue. Thank you for this report. I will have a look asap. In the meantime you can try and see if by using a custom node you solve the issue. Here a public lisk nodes that you can use in the Login page (instead of Mainnet you select Custom): https://wallet.lisknode.io

Let me know if it solves the issue, in the meantime I will try to find a clever way to fix it.

**Comment by Leniwiec44** [comment]
Unfortunately nothing changed on custom node.
![Clipboard02](https://user-images.githubusercontent.com/54898675/64286142-30d9d080-cf5d-11e9-9bef-23ececb8e61a.jpg)
![Clipboard03](https://user-images.githubusercontent.com/54898675/64286151-333c2a80-cf5d-11e9-99fc-2d862e3be965.jpg)

**Comment by hirishh** [comment]
Hey @Leniwiec44, I've fixed the issue, in the coming days I will release a new version. Thanks again for opening this bug!

**Comment by Leniwiec44** [comment]
Ok, thanks a lot!

**Comment by hirishh** [comment]
Here you go! https://www.reddit.com/r/Lisk/comments/d0z95a/liskishwallet_204beta_is_out_with_fix_on_address/

**Comment by Leniwiec44** [comment]
Problem solved. Thanks again!
