### ISSUE TITLE
Ledger Nano X Not Recognized on macOS

### ISSUE THREAD

**Issue by nottoseethesun** [hirishh/liskish-wallet#19]
### Expected behaviour

Wallet recognizes the Nano X just as it recognizes the Nano S, because Wallet notes that it has "Ledger support".  

### Actual behaviour

No hardware wallet is recognized.

### Steps to reproduce

Same as using Ledger Nano S.

**Comment by hirishh** [comment]
Hello @nottoseethesun  

Please could you try as following:
- Make sure no other software interfacing with Ledger is running
- Connect your Ledger
- Open Lisk App
- Open Liskish Wallet

let me know if you still have the issue. In case I will debug asap.

Thank you for reporting this.

**Comment by nottoseethesun** [comment]
Alright thank  you; with everything else closed, it actually does work with Nano X.  If it's not there already, maybe add "Make sure no other software interfacing with Ledger is running" would be a good thing to add to the how-to-use ("Usage").

**Comment by hirishh** [comment]
I definitely add it. Thank you!
