### ISSUE TITLE
Ledger not detected - firmware 1.6.0

### ISSUE THREAD

**Issue by krissofo** [hirishh/liskish-wallet#20]
OS:Windows
Ledger Nano S - 1.6.0
LiskishWallet - 2.0.4 beta

Please help.
Restart WIN doesn't work.

**Comment by hirishh** [comment]
Hello @krissofo 

Please could you try as following:
- Make sure no other software interfacing with Ledger is running
- Connect your Ledger
- Open Lisk App
- Open Liskish Wallet

let me know if you still have the issue. In case I will debug asap.

Thank you for reporting this.

**Comment by krissofo** [comment]
Hello,

Unfortunately, it still doesn't work (only Liskish Wallet)

-- 
Regards
/KS



niedz., 8 gru 2019 o 23:42 hirish <notifications@github.com> napisał(a):

**Comment by hirishh** [comment]
ok I will do some test and debug asap today

**Comment by hirishh** [comment]
Hello,

I'm not able to reproduce the issue. Both Ledger Nano S and X are working fine on my windows
Did you follow exactly my step to step guide?

![image](https://user-images.githubusercontent.com/7662810/70480460-0eb59880-1ae0-11ea-9fce-2a3a344fb87c.png)

**Comment by krissofo** [comment]
Hello,

1. I'm connect to my ledger nano S
2. Lisk App
[image: image.png]
3. Lishish wallet
[image: image.png]

next way...

1.  I'm connect to my ledger nano S
2. I'm connect to lisk on my ledger
3. Liskish wallet
[image: image.png]

https://github.com/LiskHQ/lisk-desktop/issues/2670

-- 
Regards
/KS



wt., 10 gru 2019 o 00:00 hirish <notifications@github.com> napisał(a):

**Comment by krissofo** [comment]
another screen

1.
[image: image.png]
I clicked on my ledger -> Lisk and I'm trying to open Liskish walle or Lisk
App (button back) and doesn't work.
I can't see my wallet and lisk

-- 
Regards
/KS



wt., 10 gru 2019 o 00:00 hirish <notifications@github.com> napisał(a):

**Comment by krissofo** [comment]
everything is OK.

I updated ledger live to newest version 1.19.2

-- 
regards
/KS



sob., 14 gru 2019 o 21:21 Kris S <krissofo@gmail.com> napisał(a):
