### ISSUE TITLE
Javascript error while installing Liskish wallet Ubuntu 18.04

### ISSUE THREAD

**Issue by Marker73** [hirishh/liskish-wallet#26]
Hello,

I tried to install "liskish-wallet-linux-x86_64-2.1.0-beta.AppImage" on Ubuntu 18.04 but I got this message :

_A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.org.chromium.Chromium.phhs2U)_

Does somebody know how to fix that issue ?

Thank u !!

**Comment by hirishh** [comment]
Hello @Marker73,

Unfortunately ubuntu 18 is still shipped with glibc 2.27.  I do not have a quick fix for you, forcing a greater version of glibc it could break functionalities of your OS. If you plan to upgrade to the new Ubuntu 20.04 LTS (Focal Fossa) you are going to have glibc 2.31 and should solve this issue.

**Comment by Marker73** [comment]
Ok Thank you
