### ISSUE TITLE
unauthorised transaction

### ISSUE THREAD

**Issue by Rastafi** [hirishh/liskish-wallet#31]
Ive bought some LSK coins in October. Ive installed Liskishwallet on my Ledger and my PC. Then I've done just one and only one transaction - to send my coins to my wallet. That's it.

Today I've opened my wallet and what do I see?

Aparrently there was another transaction, 2 weeks after the first one' withdrowing all my coins to an unknown adress. WTF?! how is it even possible without my Ledger?

**Comment by dakk** [comment]
New wallets in Lisk (whatever you use ledger or a passphrase) have to be initialized in order to avoid this problem. The software prompts the message "This account has not been initialized. It is recommended that you initialize your account by sending an outgoing transaction."

**Comment by hirishh** [comment]
Hello @Rastafi ,

I'm very sorry to hear this. You are surely victim of address mining. It is not ledger or my wallet fault. Every Lisk wallet out there, including mine, are very clear and explicit to do an outgoing transaction ASAP when you create a new wallet as you can see here

![image](https://user-images.githubusercontent.com/7662810/106488934-839e1b80-64b4-11eb-822b-8816ca8cd842.png)

If you want to know more information about what happened: https://www.reddit.com/r/Lisk/comments/jyl1it/secure_your_lisk_address_make_sure_you_have_an/

I'm sorry agian :(

**Comment by Rastafi** [comment]
so - let it be clear - you say, that because I didn't initialize my wallet some thief have stolen my goods? that's it?

**Comment by hirishh** [comment]
Yes. Unfortunately that's it.

**Comment by Rastafi** [comment]
if so, it is even hard to describe how terrible this tool is. **nie**dobre, bo polskie

**Comment by hirishh** [comment]
As I said, it's not a Liskish Wallet or Ledger problem. It's a Lisk technical limitation that is going to be addressed, hopefully, with the next hard fork. 

Insulting me doesn't fix this limitation.
