### ISSUE TITLE
Please add "Show full address" feature for Trezor device support

### ISSUE THREAD

**Issue by strmci** [hirishh/liskish-wallet#7]
### Expected behaviour
"Show full address" feature during receiving payments.

![image](https://user-images.githubusercontent.com/36126939/48064322-c256a580-e1c7-11e8-87d2-e0522507b3e2.png)

![image](https://user-images.githubusercontent.com/36126939/48064349-d5697580-e1c7-11e8-858a-d9e8ab98bcf3.png)

### Actual behaviour
"Show full address" feature missing.

**Comment by hirishh** [comment]
Hello strmci,

Thank you a lot for this issue. I've already coded this feature and I'm going to deliver it today thanks to #6 

Thank you again :)
