### ISSUE TITLE
the vote in the windows version dont work

### ISSUE THREAD

**Issue by noa969** [hirishh/liskish-wallet#9]
![unbenannt](https://user-images.githubusercontent.com/38853951/48731174-bc87a800-ec3c-11e8-855f-e4f3b9ee693b.JPG)

**Comment by noa969** [comment]
![unbenannt](https://user-images.githubusercontent.com/38853951/48731151-b09be600-ec3c-11e8-96cd-f94dbe44cb0b.JPG)

**Comment by hirishh** [comment]
Hello @noa969 
thank you for this issue. Just a quick question: Did you use a vote manager? Or you just modified manually your votes? Do you remember how many vote-unvote you had?

I'm trying to reproduce the issue

**Comment by noa969** [comment]
Hallo,
I use a webpage to klick the best votes.
Only 33 at one Time 

Patrick Haas

**Comment by noa969** [comment]
Sorry don´t work

 

Von: hirish [mailto:notifications@github.com] 
Gesendet: Donnerstag, 22. November 2018 21:25
An: hirishh/liskish-wallet
Cc: noa969; Mention
Betreff: Re: [hirishh/liskish-wallet] the vote in the windows version dont work (#9)

 

Could you try to use a custom node? In the login page you just need to select "Custom" in the Network selector and put one of those addresses. :)

liskNodes = [
"https://wallet.mylisk.com/",
"https://liskwallet.punkrock.me/",
"https://lisk-login.vipertkd.com/",
"https://wallet.lisknode.io/",
"https://lisknode.grumlin.com/",
"https://liskworld.info/",
"https://mars.liskworld.info/"
]

It should fix it. Currently there is an issue with lisk official nodes with API restrictions.

Let me know :)

**Comment by hirishh** [comment]
Try to set your time manually 1 min before. I will add a code fix in the meantime

**Comment by hirishh** [comment]
I will try to investigate and fix it asap. Thanks

**Comment by noa969** [comment]
Hello hirishh,
the Minute dont work at Windows 10 i have cange the Time manual 

Patrick Haas

**Comment by fastriffs** [comment]
I do have exactly same issue. Even with custom node. V 2.0.3

**Comment by noa969** [comment]
Das Lisk wallet von Lisk direkt geht 👌👍

Patrick Haas
